main: com.ignorelist.idontknow.plugin.Plugin
name: Plugin
version: 1.0
author: jay_jayjay
description: An plugin
commands:
    welcome:
        usage: /welcome <player>
        description: print welcome message