main: com.ignorelist.idontknow.plugin.Plugin
name: Plugin
version: 1.0
author: jay_jayjay
description: An plugin like Essentials
depend: [CS-CoreLib, Slimefun]
commands:
    welcome:
        usage: /welcome <player>